### ISSUE TITLE
Vagrant ile Uygulama Geliştirme

### ISSUE THREAD

**Issue by ecylmz** [bgebes/bgebes.github.io#2]
- [x] Vagrant kurulumu yapılmalı
- [x] vagrant-lxc kurulumu yapılmalı
- [x] lxc'nin ne olduğu öğrenilmeli
- [x] virtulbox ile lxc'nin farkı nelerdir?(avantaj, dezavantaj)
- [x] `omu/debian-stable-server` isimli vagrant-lxc imajını kullanarak, daha önce geliştirmiş olduğun uygulama için geliştirme ortamı hazırla. Örnek: https://github.com/omu/acme/blob/main/Vagrantfile

İş kaydı sonunda öğrendiklerini ve yaptıklarını yine bir dokümana yazarsın ve birlikte inceleriz.

**Comment by bgebes** [comment]
Görevler başarı ile tamamlanmış olup yakın zamanda görevler hakkında bir döküman paylaşılacaktır.

**Comment by bgebes** [comment]
Döküman, çekirge kanalında paylaşılmıştır.
